services:

  # =========================
  # Eureka Server
  # =========================
  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network


  # =========================
  # MongoDB Client
  # =========================
  mongodb-client:
    image: mongo:7
    container_name: mongodb-client
    volumes:
      - client-mongo-data:/data/db
    networks:
      - microservices-network


  # =========================
  # PostgreSQL Product
  # =========================
  postgres-product:
    image: postgres:17
    container_name: postgres-product
    environment:
      POSTGRES_DB: dbproduct
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - product-postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-network


  # =========================
  # PostgreSQL Order
  # =========================
  postgres-order:
    image: postgres:17
    container_name: postgres-order
    environment:
      POSTGRES_DB: dborder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - order-postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-network


  # =========================
  # Client Service
  # =========================
  client-service:
    build:
      context: ./client-service
    container_name: client-service
    expose:
      - "8083"
    depends_on:
      - eureka-server
      - mongodb-client
    networks:
      - microservices-network


  # =========================
  # Product Service
  # =========================
  product-service:
    build:
      context: ./product-service
    container_name: product-service
    expose:
      - "8081"
    depends_on:
      - eureka-server
      - postgres-product
    networks:
      - microservices-network


  # =========================
  # Order Service
  # =========================
  order-service:
    build:
      context: ./order-service
    container_name: order-service
    expose:
      - "8082"
    depends_on:
      - eureka-server
      - postgres-order
      - client-service
      - product-service
    networks:
      - microservices-network


  # =========================
  # API Gateway
  # =========================
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - client-service
      - product-service
      - order-service
    networks:
      - microservices-network


# =========================
# Networks
# =========================
networks:
  microservices-network:
    driver: bridge


# =========================
# Volumes
# =========================
volumes:
  client-mongo-data:
  product-postgres-data:
  order-postgres-data: