server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/phabsokthin/spring_boot_microservice
          default-label: main
          search-paths:
            - config-repo